name: beaut
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - python=3.12
  - pip
  - networkx
  - pandas=2.2.1
  - scipy
  - scikit-learn
  - tqdm
  - nltk
  - pip:
      - biotite
      - fair-esm==2.0.0
      - --extra-index-url https://download.pytorch.org/whl/cu126
      - torch==2.6.0
      - torchvision==0.21.0
      - torchaudio==2.6.0
