all:
	gcc -o Step3-PM_typeA Step3-PM_typeA.c -lm
	gcc -o Step3-PM_typeB Step3-PM_typeB.c -lm

	g++ -o cabbage-file_maker/Step0-cabbage_core cabbage-file_maker/Step0-cabbage_core.cpp
	g++ -o cabbage-file_maker/Step0-cabbage_decoder cabbage-file_maker/Step0-cabbage_core.cpp
	gcc -o cabbage-file_maker/Step0-END-FILE cabbage-file_maker/Step0-END-FILE.c
